### ISSUE TITLE
bundle tests are failing wiht 3.0.0 official

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-resources#104]
```
Error:
ModelTests#test_model_articulation1_bundle_no_git_osw:
RuntimeError: Exit code 1:
W, [2020-04-27T22:39:24.915438 #6719]  WARN -- : Bundle activated but ENV['BUNDLE_WITHOUT'] is not set
Error executing argv: ["--bundle", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_no_git/Gemfile", "--bundle_path", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_no_git/gems", "run", "-w", "/home/julien/Software/Others/OpenStudio-resources/testruns/model_articulation1_bundle_no_git.osw/in.osw"]
Error: Could not find openstudio-standards-0.2.11 in any of the sources in /home/julien/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'
/home/julien/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
/home/julien/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
/home/julien/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
/home/julien/.rvm/gems/ruby-2.5.5/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
:/openstudio_cli.rb:557:in `parse_main_args'
:/openstudio_cli.rb:727:in `execute'
:/openstudio_cli.rb:1757:in `<main>'
eval:149:in `eval'
eval:149:in `require_embedded_absolute'
eval:123:in `block in require'
eval:117:in `each'
eval:117:in `require'
eval:3:in `<main>'

    /home/julien/Software/Others/OpenStudio-resources/test_helpers.rb:352:in `block in run_command'
    :/ruby/2.5.0/open3.rb:205:in `popen_run'
    :/ruby/2.5.0/open3.rb:95:in `popen3'
    /home/julien/Software/Others/OpenStudio-resources/test_helpers.rb:336:in `run_command'
    /home/julien/Software/Others/OpenStudio-resources/test_helpers.rb:699:in `sim_test'
    /home/julien/Software/Others/OpenStudio-resources/model_tests.rb:999:in `test_model_articulation1_bundle_no_git_osw'

Failure:
ModelTests#test_model_articulation1_bundle_git_osw [/home/julien/Software/Others/OpenStudio-resources/model_tests.rb:1051]
Minitest::Assertion: Expected nil to be truthy.

2 tests, 9 assertions, 1 failures, 1 errors, 0 skips
```

**Comment by brianlball** [comment]
@kbenne @tijcolem is this related/relevant to our bundle discussion the other day?

**Comment by jmarrec** [comment]
Actually it seems that running them in Series rather than in parallel makes them pass.

I probably have an error in my helper script though, need to investigate this:

```
Finished tests in 35.595116s, 0.0281 tests/s, 0.1967 assertions/s.


Failure:
ModelTests#test_model_articulation1_bundle_no_git_osw [/home/julien/Software/Others/OpenStudio-resources/model_tests.rb:1020]
Minitest::Assertion: Expected nil to be truthy.

1 tests, 7 assertions, 1 failures, 0 errors, 0 skips

```
