### ISSUE TITLE
model_articulation1_bundle_git is failing with v9.5.0-IOFreeze / ruby 2.7.2

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-resources#134]
This could be a misconfiguration issue on my machine, but the no_git one works for me...

```
# Running tests with run options :

Running for OpenStudio 3.1.1-alpha+2ddf66d1fc
Running for OpenStudio 3.1.1-alpha+2ddf66d1fc (Previous=3.1.0)

# Running tests with run options -n /model_articulation1_bundle_git/ --seed 6219:

[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path './gems'`, and stop using this flag
Fetching https://github.com/nrel/openstudio-workflow-gem.git
Fetching gem metadata from http://rubygems.org/
Resolving dependencies...
Using bundler 2.1.4
Using openstudio-workflow 2.2.0 from https://github.com/nrel/openstudio-workflow-gem.git (at v2.2.0@e5a8f7f)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into `./gems`
Writing lockfile to /home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/Gemfile.lock
E

Finished tests in 19.170302s, 0.0522 tests/s, 0.1043 assertions/s.


Error:
ModelTests#test_model_articulation1_bundle_git_osw:
RuntimeError: Exit code 1:
I, [2021-03-01T13:26:42.601911 #22433]  INFO -- : CLI Parsed Inputs: ["--verbose", "--bundle", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/Gemfile", "--bundle_path", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/gems"] "run" ["--debug", "-w", "/home/julien/Software/Others/OpenStudio-resources/testruns/model_articulation1_bundle_git.osw/in.osw"]
D, [2021-03-01T13:26:42.601951 #22433] DEBUG -- : Main arguments are ["--verbose", "--bundle", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/Gemfile", "--bundle_path", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/gems"]
D, [2021-03-01T13:26:42.601960 #22433] DEBUG -- : Sub-command is run
D, [2021-03-01T13:26:42.601972 #22433] DEBUG -- : Sub-arguments are ["--debug", "-w", "/home/julien/Software/Others/OpenStudio-resources/testruns/model_articulation1_bundle_git.osw/in.osw"]
D, [2021-03-01T13:26:42.601988 #22433] DEBUG -- : Parsing main_args ["--verbose", "--bundle", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/Gemfile", "--bundle_path", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/gems"]
I, [2021-03-01T13:26:42.602001 #22433]  INFO -- : Setting BUNDLE_GEMFILE to /home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/Gemfile
I, [2021-03-01T13:26:42.602012 #22433]  INFO -- : Setting BUNDLE_PATH to /home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/gems
I, [2021-03-01T13:26:42.602029 #22433]  INFO -- : Bundle activated but ENV['BUNDLE_WITHOUT'] is not set
I, [2021-03-01T13:26:42.602038 #22433]  INFO -- : Setting BUNDLE_WITHOUT to 'test'
D, [2021-03-01T13:26:42.791614 #22433] DEBUG -- : Found system gem bundler 2.1.4, overrides embedded gem
D, [2021-03-01T13:26:42.807819 #22433] DEBUG -- : Adding dependency on jaro_winkler '~> 1.5.4'
D, [2021-03-01T13:26:42.807852 #22433] DEBUG -- : Adding dependency on pycall '~> 1.2.1'
D, [2021-03-01T13:26:42.807868 #22433] DEBUG -- : Adding dependency on sqlite3 '~> 1.3.13.20180326210955'
D, [2021-03-01T13:26:42.807883 #22433] DEBUG -- : Adding dependency on addressable '~> 2.7.0'
D, [2021-03-01T13:26:42.807899 #22433] DEBUG -- : Adding dependency on ansi '~> 1.5.0'
D, [2021-03-01T13:26:42.807912 #22433] DEBUG -- : Adding dependency on ast '~> 2.4.2'
D, [2021-03-01T13:26:42.807925 #22433] DEBUG -- : Adding dependency on bcl '~> 0.7.0'
D, [2021-03-01T13:26:42.807939 #22433] DEBUG -- : Adding dependency on builder '~> 3.2.4'
D, [2021-03-01T13:26:42.807951 #22433] DEBUG -- : Adding dependency on bundler '~> 2.1.4'
D, [2021-03-01T13:26:42.807964 #22433] DEBUG -- : Adding dependency on docile '~> 1.3.5'
D, [2021-03-01T13:26:42.807977 #22433] DEBUG -- : Adding dependency on faraday '~> 1.0.1'
D, [2021-03-01T13:26:42.807990 #22433] DEBUG -- : Adding dependency on git '~> 1.6.0'
D, [2021-03-01T13:26:42.808003 #22433] DEBUG -- : Adding dependency on macaddr '~> 1.7.2'
D, [2021-03-01T13:26:42.808019 #22433] DEBUG -- : Adding dependency on minitar '~> 0.9'
D, [2021-03-01T13:26:42.808032 #22433] DEBUG -- : Adding dependency on minitest '~> 5.14.3'
D, [2021-03-01T13:26:42.808048 #22433] DEBUG -- : Adding dependency on minitest-reporters '~> 1.4.3'
D, [2021-03-01T13:26:42.808061 #22433] DEBUG -- : Adding dependency on multipart-post '~> 2.1.1'
D, [2021-03-01T13:26:42.808073 #22433] DEBUG -- : Adding dependency on octokit '~> 4.18.0'
D, [2021-03-01T13:26:42.808086 #22433] DEBUG -- : Adding dependency on oga '~> 3.2'
D, [2021-03-01T13:26:42.808099 #22433] DEBUG -- : Adding dependency on openstudio-extension '~> 0.4.0'
D, [2021-03-01T13:26:42.808111 #22433] DEBUG -- : Adding dependency on openstudio-standards '~> 0.2.12'
D, [2021-03-01T13:26:42.808124 #22433] DEBUG -- : Adding dependency on openstudio-workflow '~> 2.2.0'
D, [2021-03-01T13:26:42.808137 #22433] DEBUG -- : Adding dependency on openstudio_measure_tester '~> 0.3.0'
D, [2021-03-01T13:26:42.808149 #22433] DEBUG -- : Adding dependency on parallel '~> 1.19.1'
D, [2021-03-01T13:26:42.808162 #22433] DEBUG -- : Adding dependency on parser '~> 3.0.0.0'
D, [2021-03-01T13:26:42.808175 #22433] DEBUG -- : Adding dependency on powerpack '~> 0.1.3'
D, [2021-03-01T13:26:42.808193 #22433] DEBUG -- : Adding dependency on public_suffix '~> 4.0.6'
D, [2021-03-01T13:26:42.808206 #22433] DEBUG -- : Adding dependency on rainbow '~> 3.0.0'
D, [2021-03-01T13:26:42.808218 #22433] DEBUG -- : Adding dependency on rake '~> 13.0.3'
D, [2021-03-01T13:26:42.808230 #22433] DEBUG -- : Adding dependency on rchardet '~> 1.8.0'
D, [2021-03-01T13:26:42.808243 #22433] DEBUG -- : Adding dependency on rexml '~> 3.2.4'
D, [2021-03-01T13:26:42.808256 #22433] DEBUG -- : Adding dependency on rubocop '~> 0.54.0'
D, [2021-03-01T13:26:42.808268 #22433] DEBUG -- : Adding dependency on rubocop-checkstyle_formatter '~> 0.4.0'
D, [2021-03-01T13:26:42.808281 #22433] DEBUG -- : Adding dependency on ruby-ll '~> 2.1.2'
D, [2021-03-01T13:26:42.808293 #22433] DEBUG -- : Adding dependency on ruby-ole '~> 1.2.12.2'
D, [2021-03-01T13:26:42.808307 #22433] DEBUG -- : Adding dependency on ruby-progressbar '~> 1.11.0'
D, [2021-03-01T13:26:42.808319 #22433] DEBUG -- : Adding dependency on rubyzip '~> 2.3.0'
D, [2021-03-01T13:26:42.808332 #22433] DEBUG -- : Adding dependency on sawyer '~> 0.8.2'
D, [2021-03-01T13:26:42.808351 #22433] DEBUG -- : Adding dependency on simplecov '~> 0.18.5'
D, [2021-03-01T13:26:42.808367 #22433] DEBUG -- : Adding dependency on simplecov-html '~> 0.12.3'
D, [2021-03-01T13:26:42.808382 #22433] DEBUG -- : Adding dependency on spreadsheet '~> 1.2.6'
D, [2021-03-01T13:26:42.808395 #22433] DEBUG -- : Adding dependency on systemu '~> 2.6.5'
D, [2021-03-01T13:26:42.808407 #22433] DEBUG -- : Adding dependency on unicode-display_width '~> 1.7.0'
D, [2021-03-01T13:26:42.808420 #22433] DEBUG -- : Adding dependency on uuid '~> 2.3.9'
D, [2021-03-01T13:26:42.808432 #22433] DEBUG -- : Adding dependency on yamler '~> 0.1.0'
D, [2021-03-01T13:26:42.808444 #22433] DEBUG -- : Adding dependency on zliby '~> 0.0.5'
D, [2021-03-01T13:26:42.841544 #22433] DEBUG -- : Processing 46 activation requests
D, [2021-03-01T13:26:42.843365 #22433] DEBUG -- : Activating gem /home/julien/.conan/data/openstudio_ruby/2.7.2/nrel/testing/build/9f9bc9c7ba86f123c671ad0cd57bd027161f8634/Ruby-prefix/src/Ruby-install/lib/ruby/gems/2.7.0/specifications/bundler-2.1.4.gemspec
I, [2021-03-01T13:26:46.350938 #22433]  INFO -- : without_groups = test
I, [2021-03-01T13:26:46.350962 #22433]  INFO -- : g = default
I, [2021-03-01T13:26:46.350973 #22433]  INFO -- : Bundling with groups [default]
Error executing argv: ["--verbose", "--bundle", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/Gemfile", "--bundle_path", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_git/gems", "run", "--debug", "-w", "/home/julien/Software/Others/OpenStudio-resources/testruns/model_articulation1_bundle_git.osw/in.osw"]
Error: undefined method `from_stub' for nil:NilClass in :/ruby/2.7.0/bundler/source/git.rb:322:in `load_gemspec'
:/ruby/2.7.0/bundler/source/path.rb:173:in `block in load_spec_files'
:/ruby/2.7.0/bundler/source/path.rb:172:in `each'
:/ruby/2.7.0/bundler/source/path.rb:172:in `load_spec_files'
:/ruby/2.7.0/bundler/source/git.rb:203:in `load_spec_files'
:/ruby/2.7.0/bundler/source/path.rb:107:in `local_specs'
:/ruby/2.7.0/bundler/source/git.rb:170:in `specs'
:/ruby/2.7.0/bundler/lazy_specification.rb:75:in `__materialize__'
:/ruby/2.7.0/bundler/spec_set.rb:83:in `block in materialize'
:/ruby/2.7.0/bundler/spec_set.rb:80:in `map!'
:/ruby/2.7.0/bundler/spec_set.rb:80:in `materialize'
:/ruby/2.7.0/bundler/definition.rb:170:in `specs'
:/ruby/2.7.0/bundler/definition.rb:237:in `specs_for'
:/openstudio_cli.rb:637:in `parse_main_args'
:/openstudio_cli.rb:766:in `execute'
:/openstudio_cli.rb:1796:in `<main>'
eval:177:in `eval'
eval:177:in `require_embedded_absolute'
eval:162:in `block in require_embedded'
eval:156:in `each'
eval:156:in `require_embedded'
eval:115:in `require'
eval:3:in `<main>'

    /home/julien/Software/Others/OpenStudio-resources/test_helpers.rb:346:in `block in run_command'
    :/ruby/2.7.0/open3.rb:219:in `popen_run'
    :/ruby/2.7.0/open3.rb:101:in `popen3'
    /home/julien/Software/Others/OpenStudio-resources/test_helpers.rb:334:in `run_command'
    /home/julien/Software/Others/OpenStudio-resources/test_helpers.rb:682:in `sim_test'
    /home/julien/Software/Others/OpenStudio-resources/model_tests.rb:1207:in `test_model_articulation1_bundle_git_osw'

1 tests, 2 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by jmarrec** [comment]
I personally also cannot run this test with 3.1.0 official and workflow-gem 2.0.1 (checkout develop at 0c8243327bd879943cae376e977a0d6cbfa505ee)

But that's more of a problem of a conflict between bundler 2.1.0 and 2.1.4...
