### ISSUE TITLE
Cannot run tests from Windows command prompt 

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio-resources#40]
Here is the call stack, seems like powerbar is trying to make a system call to `tput cols`.  I have to run in git bash as a workaround.

```
The system cannot find the path specified.
The system cannot find the path specified.
:/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:316:in ``': No such file or di
rectory - tput cols (Errno::ENOENT)
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:316:in `terminal_width'
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:240:in `bar'
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:248:in `h_bar'
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:351:in `block (2 levels) in render_template'
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:348:in `gsub'
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:348:in `block in render_template'
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:346:in `gsub'
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:346:in `render_template'
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:226:in `render'
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:218:in `show'
        from :/ruby/2.2.0/gems/powerbar-1.0.18/lib/powerbar.rb:173:in `close'
        from :/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporters/progress_reporter.rb:92:in `after_suites'
        from :/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:97:in `public_send'
        from :/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:97:in `block in trigger_callback'
        from :/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:97:in `each'
        from :/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:97:in `trigger_callback'
        from :/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:39:in `ensure in _run_suites'
        from :/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:39:in `_run_suites'
        from :/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:877:in `_run_anything'
        from :/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1085:in `run_tests'
        from :/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:30:in `run_tests'
        from :/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1072:in `block in _run'
        from :/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1071:in `each'
        from :/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1071:in `_run'
        from :/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1059:in `run'
        from :/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:795:in `block in autorun'
```

**Comment by macumber** [comment]
@jmarrec FYI

**Comment by macumber** [comment]
I added minitest-reporters here, https://github.com/NREL/OpenStudio/blob/0aa42b730a542204d730cef692df3c1cfd9992d4/dependencies/ruby/Gemfile#L15

Seems like this is a really old version, not sure why I picked that

**Comment by macumber** [comment]
Thinking that I want to try updating minitest and minitest reporters after 2.5.0 release.  @nllong FYI

**Comment by nllong** [comment]
Yes, I did this on the update measure templates branch https://github.com/NREL/OpenStudio/pull/3014/files#diff-3a5a5d3362a3c336de1be92bd6f4acd3R13

which pulls in these dependencies https://github.com/NREL/OpenStudio-measure-tester-gem/blob/develop/openstudio_measure_tester.gemspec#L29

**Comment by macumber** [comment]
Cool, thanks.  For OpenStudio I use exact gem versions so our builds are completely reproducible, just an FYI

**Comment by nllong** [comment]
okay. I can update this on the OpenStudio Measure Tester Gem, since that
will be what drives the dependencies in OpenStudio.

**Comment by nllong** [comment]
versions are locked down now (https://github.com/NREL/OpenStudio-measure-tester-gem/blob/develop/openstudio_measure_tester.gemspec#L26-L34)

**Comment by jmarrec** [comment]
Are there any remaining action items on this issue @macumber?

**Comment by jmarrec** [comment]
I can run tests using the CLI `openstudio` in cmd.exe just fine
