### ISSUE TITLE
Fix 

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-resources#43]
`afn_single_zone_ac.rb` is failing.

Test was added in https://github.com/NREL/OpenStudio-resources/pull/39

With current OpenStudio develop, `run.log` shows:

```
[16:01:23.770659 ERROR] Found error in state 'translator' with message ["std::bad_cast::/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/model.rb:66:in `translateModel'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/model.rb:66:in `translate_to_energyplus'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/jobs/run_translation.rb:54:in `perform'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:261:in `step'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:210:in `run'\n:/openstudio_cli.rb:821:in `execute'\n:/openstudio_cli.rb:620:in `execute'\n:/openstudio_cli.rb:1547:in `<main>'\neval:85:in `eval'\neval:85:in `require_embedded_absolute'\neval:70:in `block in require'\neval:64:in `each'\neval:64:in `require'\neval:2:in `<main>'"]}
```

-----

`afn_single_zone_nv.osm` is failing. 

|E+|8.6.0|8.7.0|8.8.0|8.9.0|n_fail|n_missing|n_fail+missing|OS|2.0.4|2.0.5|2.1.0|2.1.1|2.1.2|2.2.0|2.2.1|2.2.2|2.3.0|2.3.1|2.4.0|2.4.1|2.4.3|2.4.4|Test|Type|afn_single_zone_ac|osm|rb|afn_single_zone_nv|osm|rb|
|--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |
|None|None|None|None|None|None|None|None|None|None|None|None|None|None|0|0|0|
|Fail|1|13|14|
|N/A|N/A|N/A|N/A|N/A|N/A|N/A|N/A|N/A|N/A|N/A|N/A|Success|Fail|1|0|1|
|N/A|N/A|N/A|N/A|N/A|N/A|N/A|N/A|N/A|N/A|N/A|N/A|Success|Success|0|0|0|

**Comment by macumber** [comment]
The AC version of this test is not yet working so we have commented out

**Comment by jmarrec** [comment]
`afn_single_zone_nv.osm` is failing in 2.5.0 official (was working in 2.4.3), run.log shows:

```
[08:04:33.543566 ERROR] Found error in state 'translator' with message ["/home/bldadmin/openstudio/openstudiocore/src/model/AirflowNetworkZone.cpp@110 : Object of type 'OS:AirflowNetworkZone' and named '{ff634789-3b5c-4747-98c9-153c63b0c8b5}' does not have an Thermal Zone attached.::/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/model.rb:66:in `translateModel'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/model.rb:66:in `translate_to_energyplus'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/jobs/run_translation.rb:54:in `perform'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:261:in `step'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:210:in `run'\n:/openstudio_cli.rb:821:in `execute'\n:/openstudio_cli.rb:620:in `execute'\n:/openstudio_cli.rb:1547:in `<main>'\neval:85:in `eval'\neval:85:in `require_embedded_absolute'\neval:70:in `block in require'\neval:64:in `each'\neval:64:in `require'\neval:2:in `<main>'"]}
```

**Comment by jmarrec** [comment]
This a missing version translation thing.
In 2.4.3, there was no "Name"  field, which was introduced in 2.5.0, but not handled in Version translation.

2_4_3/OpenStudio.idd
```
OS:AirflowNetworkZone,
      \min-fields 9
      \memo This object is used to simultaneously control a thermal zone's window and door openings,
      \memo both exterior and interior.
  A1, \field Handle
      \type handle
      \required-field
  A2, \field Thermal Zone Name
      \required-field
      \type object-list
      \object-list ThermalZoneNames
      \note Enter the zone name where ventilation control is required.
[...]
```

2_5_0/OpenStudio.idd
```
OS:AirflowNetworkZone,
      \min-fields 9
      \memo This object is used to simultaneously control a thermal zone's window and door openings,
      \memo both exterior and interior.
  A1, \field Handle
      \type handle
      \required-field
  A2, \field Name
      \required-field
      \type alpha
      \reference AirflowNetworkNodeAndZoneNames
  A3, \field Thermal Zone Name
      \required-field
      \type object-list
      \object-list ThermalZoneNames
      \note Enter the zone name where ventilation control is required.
[...]
```

**Comment by jmarrec** [comment]
The `test_afn_single_zone_nv_osm` is now working after changes done in https://github.com/NREL/OpenStudio/pull/3085

The AC test (and underlying model API changes) are still on a TODO
